-- <ScriptOptions statementTerminator=";" />
CREATE SCHEMA "orquestador";
GRANT ALTERIN ON SCHEMA "orquestador" TO PUBLIC WITH GRANT OPTION;
GRANT ALTERIN ON SCHEMA "orquestador" TO USER DB2ADMIN WITH GRANT OPTION;
GRANT ALTERIN ON SCHEMA "orquestador" TO USER DIEGO WITH GRANT OPTION;
GRANT ALTERIN ON SCHEMA "orquestador" TO ROLE SYSDEBUG WITH GRANT OPTION;
GRANT ALTERIN ON SCHEMA "orquestador" TO ROLE SYSDEBUGPRIVATE WITH GRANT OPTION;
GRANT CREATEIN ON SCHEMA "orquestador" TO PUBLIC WITH GRANT OPTION;
GRANT CREATEIN ON SCHEMA "orquestador" TO USER DB2ADMIN WITH GRANT OPTION;
GRANT CREATEIN ON SCHEMA "orquestador" TO USER DIEGO WITH GRANT OPTION;
GRANT CREATEIN ON SCHEMA "orquestador" TO ROLE SYSDEBUG WITH GRANT OPTION;
GRANT CREATEIN ON SCHEMA "orquestador" TO ROLE SYSDEBUGPRIVATE WITH GRANT OPTION;
GRANT DROPIN ON SCHEMA "orquestador" TO PUBLIC WITH GRANT OPTION;
GRANT DROPIN ON SCHEMA "orquestador" TO USER DB2ADMIN WITH GRANT OPTION;
GRANT DROPIN ON SCHEMA "orquestador" TO USER DIEGO WITH GRANT OPTION;
GRANT DROPIN ON SCHEMA "orquestador" TO ROLE SYSDEBUG WITH GRANT OPTION;
GRANT DROPIN ON SCHEMA "orquestador" TO ROLE SYSDEBUGPRIVATE WITH GRANT OPTION;
