-- <ScriptOptions statementTerminator=";" />
CREATE LARGE TABLESPACE USERSPACE001 IN DATABASE PARTITION GROUP IBMDEFAULTGROUP PAGESIZE 4096 MANAGED BY AUTOMATIC STORAGE USING STOGROUP IBMSTOGROUP AUTORESIZE YES BUFFERPOOL IBMDEFAULTBP OVERHEAD INHERIT TRANSFERRATE INHERIT DROPPED TABLE RECOVERY ON DATA TAG INHERIT;
GRANT USE OF TABLESPACE USERSPACE001 TO PUBLIC WITH GRANT OPTION;
GRANT USE OF TABLESPACE USERSPACE001 TO USER DB2ADMIN WITH GRANT OPTION;
GRANT USE OF TABLESPACE USERSPACE001 TO USER DIEGO WITH GRANT OPTION;
GRANT USE OF TABLESPACE USERSPACE001 TO ROLE SYSDEBUG WITH GRANT OPTION;
GRANT USE OF TABLESPACE USERSPACE001 TO ROLE SYSDEBUGPRIVATE WITH GRANT OPTION;
